language: node_js
node_js:
- '8'
cache:
  apt: true
  directories:
  - node_modules
addons:
  ssh_known_hosts: $TARGET_IP
before_install:
- openssl aes-256-cbc -K $encrypted_6586bb378001_key -iv $encrypted_6586bb378001_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- npm install -g cnpm --registry=https://registry.npm.taobao.org
- cnpm install umi
install:
- cnpm install
script:
- umi build
after_success:
- ls -al ~/.ssh
- chmod 600 ~/.ssh/id_rsa
- tar -zcf dist.tar.gz ./dist
- scp dist.tar.gz root@$TARGET_IP:/www/
- ssh root@$TARGET_IP -o StrictHostKeyChecking=no  'cd /www && rm -rf ./zhangDaYe
  && tar -xzf dist.tar.gz && rm -rf dist.tar.gz && mv dist zhangDaYe && exit 0'
