language: node_js

node_js:
- '8'

cache:
  apt: true
  directories:
  - node_modules

addons:
  ssh_known_hosts: 120.79.188.124

before_install:
- openssl aes-256-cbc -K $encrypted_6586bb378001_key -iv $encrypted_6586bb378001_iv
  -in ssh_id.enc -out ./ssh_id -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 120.79.188.124\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git config --global user.name "fXy-during"
- git config --global user.email "fxy1044667399@163.com"
- npm install -g cnpm --registry=https://registry.npm.taobao.org
- cnpm install umi

install:
- cnpm install

script:
- umi build

after_success:
- tar -zcf zhangDaYe.tar.gz ./dist
- scp zhangDaYe.tar.gz root@120.79.188.124:/www/
- ssh root@120.79.188.124 -o StrictHostKeyChecking=no  'cd /www && rm -rf ./zhangDaYe && tar -xzf ./zhangDaYe.tar.gz && rm -rf zhangDaYe.tar.gz && exit'
