language: node_js

node_js:
  - "8"

cache:
  apt: true
  directories:
    - node_modules

before_install:
#  配置git
  - git config --global user.name "fXy-during"
  - git config --global user.email "fxy1044667399@163.com"
  - cnpm install umi

install: 
  - cnpm install 


script: 
  - umi build